name: Lighthouse
on: [push]
jobs:
  lhci:
    name: Lighthouse
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 10.x
        uses: actions/setup-node@v1
        with:
          node-version: 10.x
      - name: Use Python 3.9.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.x'
      - name: Install requirements
        run: |
          npm install -g @lhci/cli@0.6.x puppeteer
          python3 -m pip install -r requirements.txt
      - name: Run Lighthouse
        run: |
          lhci autorun
        env:
          LHCI_GITHUB_APP_TOKEN: ${{ secrets.LHCI_GITHUB_APP_TOKEN }}
